name: Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    PYTHON-VERSION: 3.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON-VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON-VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry update
          poetry install
      - name: Generate requirements.txt
        run: |
          set -eux
          mkdir -p ${GITHUB_WORKSPACE}/dist
          # Prepare requirements.txt for dependencies
          poetry export -f requirements.txt --output ${GITHUB_WORKSPACE}/dist/requirements.txt --without=dev,test --with-credentials
          ls ${GITHUB_WORKSPACE}/dist/
      - name: Build Wheels for Dependencies
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/dist/wheels
          # Build wheels for dependencies
          pip wheel -r ${GITHUB_WORKSPACE}/dist/requirements.txt --wheel-dir ${GITHUB_WORKSPACE}/dist/wheels
          ls ${GITHUB_WORKSPACE}/dist/wheels
      - name: Build Wheel for Package
        run: |
          # Build wheel for package
          poetry build --directory=${GITHUB_WORKSPACE} -f wheel
          ls ${GITHUB_WORKSPACE}/dist/
          mv ${GITHUB_WORKSPACE}/dist/*.whl ${GITHUB_WORKSPACE}/dist/wheels
          ls ${GITHUB_WORKSPACE}/dist/wheels
      - name: Build Docker Image
        run: |
          docker build \
            --context ${GITHUB_WORKSPACE} \
            --build-arg FACTORIO_VERSION=latest \
            --build-arg FACTORIO_SAVE_PATH=/opt/app/saves/save.zip \
            -t ${GITHUB_REPOSITORY}:${GITHUB_SHA} \
            .
          docker tag ${GITHUB_REPOSITORY}:${GITHUB_SHA} ${GITHUB_REPOSITORY}:latest