name: Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    PYTHON-VERSION: 3.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON-VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON-VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry update
          poetry install
      - name: Build wheels
        run: |
          . ${GITHUB_WORKSPACE}/.venv/bin/activate
          # Prepare requirements.txt for dependencies
          poetry export -f requirements.txt --output ${GITHUB_WORKSPACE}/dist/requirements.txt --without=dev,test --with-credentials
          mkdir -p ${GITHUB_WORKSPACE}/dist/wheels
          # Build wheels for dependencies
          pip wheel -r ${GITHUB_WORKSPACE}/dist/requirements.txt --wheel-dir ${GITHUB_WORKSPACE}/dist/wheels
          # Build wheel for package
          poetry build -c ${GITHUB_WORKSPACE} -f wheel
          mv ${GITHUB_WORKSPACE}/dist/*.whl ${GITHUB_WORKSPACE}/dist/wheels
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg FACTORIO_VERSION=latest \
            --build-arg FACTORIO_SAVE_PATH=/opt/app/saves/save.zip \
            -t ${GITHUB_REPOSITORY}:${GITHUB_SHA} \
            .
          docker tag ${GITHUB_REPOSITORY}:${GITHUB_SHA} ${GITHUB_REPOSITORY}:latest